<?php

namespace common\widgets;

use common\models\Profile;
use yii\bootstrap5\Widget;

class admin extends Widget
{
    public $view = 'admin';
    public $admin;

    public function run()
    {
//        parent::run(); // TODO: Change the autogenerated stub
        $this->admin = Profile::find()->where(['created_by' => \Yii::$app->user->identity->username])->one();
        return $this->render($this->view, [
            'admin' => $this->admin,
        ]);
    }
}